language: node_js
node_js:
  - "5.9.0"
  - "5"
  - "6"

sudo: required
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y ruby-full
before_script:
  - npm install -g gulp
script: gulp
